### ISSUE TITLE
Passthrough fails with @BuiltinService

### ISSUE THREAD

**Issue by mathieucarbou** [Terracotta-OSS/tc-passthrough-testing#14]
If I annotated a service provider with `@BuiltinService` and register it like this:

`activeServer.registerServiceProvider(new MonitoringServiceProvider(), null);` // or any config 

then it fails in the assertion below in `PassthroughServiceRegistry`:

```
  public <T> T getService(ServiceConfiguration<T> configuration) {
    Object builtInService = null != this.owningEntityContainer?this.getBuiltIn(configuration):null;
    Object externalService = this.getExternal(configuration);
    Assert.assertTrue(null == builtInService || null == externalService);
    return null != builtInService?builtInService:externalService;
  }
```

Because the service is found in both the builtin and external list.

If I do not register the service with `.registerServiceProvider()`, then my server entity is able to discover the service and call:

`IMonitoringProducer producer = registry.getService(new BasicServiceConfiguration<>(IMonitoringProducer.class));`

And the object is there. BUT the underlying monitoring tree is completely void: there is no platform root node and no information about platform.

It's like the service was lazy-loaded and thus platform was not able to expose things.

**Comment by AbfrmBlr** [comment]
I think `findClasspathBuiltinServices` in `PassthroughServer` is doing the service discovery part by calling `ServiceLoader.load` and then checks for `BuiltinService` annotations.

**Comment by mathieucarbou** [comment]
NB: This issue currently is needed and blocks us from completing our current work for:

- Terracotta-OSS/terracotta-platform#127
- ehcache/ehcache3#1008

**Comment by anthonydahanne** [comment]
@AbfrmBlr what could be the way to have the builtinService correctly setup ?

**Comment by jd0-sag** [comment]
The main problem here is that the "platform entity" (the fake entity we use to look up services for the platform's own uses) doesn't have an `owningEntityContainer` and we require that in order to use services registered as built-in.  I will have to look up why this special-case exists but I suspect that the actual issue lies with our use of `@BuiltinService`-annotated `ServiceProvider` instances as though they were one of the literally "built-in service implementations" (those provided by the implementation, itself).

Adding the annotation caused the provider to be registered in this special list instead of the one services normally end up in.  This is why the monitoring tree was empty:  the attempt to look up the service explicitly failed.

The later assertion failure makes more sense in that, since you are trying to avoid this bug by effectively "double-registering" the provider, it complains that it found an ambiguous answer.

I will look into why we put these in the other provider container since that is the part of this which seems most odd.  Failing that, it may be possible to remove the logic which explicitly forbids entities like this from using built-ins, but that seems like a less likely answer (since it is a very deliberate action).

**Comment by jd0-sag** [comment]
In a very small experiment, I changed passthrough to add `@BuildinService`-annotated providers to the normal collection of providers and it seems to resolve the issue.

I will do some more experiments and try to unearth the original rationale but this seems to be the right track.  Note that the multi-process server does something similar so we will also need to look at that.

Additionally, if any of these changes are to be made, the existing containers will need to be renamed since their internal names relate to them being "built-in" but that term now has a mixed meaning.

**Comment by AbfrmBlr** [comment]
@anthonydahanne Since the all the annotated Built-in services are discovered and registered as built in services, the service worked just fine for me as there was no config required and meta-inf service file just helped there. As I understood, since it is built in service the platform will look up for it using service discovery(which it is doing) thus I never registered explicitly. I think what @jd0-sag is trying to say that passthrough testing wants to keep a distinction between Built-InServices: one  provided by platform and the other provided by entities.

**Comment by mathieucarbou** [comment]
Talked to @jd0-sag : no need to call `activeServer.registerServiceProvider();` for `@BuildinService` services.

So I started to change all our test. They currently fail because the tree is empty.

@jd0-sag : do you have an ETA for the bugfix PR ?

Thanks :-)
